// <auto-generated />
using ChallengeTecnico_Ears.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChallengeTecnico_Ears.Migrations
{
    [DbContext(typeof(ContextChallenge))]
    [Migration("20240523204702_InitialDef")]
    partial class InitialDef
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChallengeTecnico_Ears.Models.OfficeModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("CUIT")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdPerson")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdPerson");

                    b.ToTable("T_Offices");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Active = true,
                            CUIT = 123456789,
                            CompanyName = "Company1",
                            IdPerson = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Active = false,
                            CUIT = 987654321,
                            CompanyName = "Company2",
                            IdPerson = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Active = true,
                            CUIT = 246810121,
                            CompanyName = "Company3",
                            IdPerson = 3L
                        },
                        new
                        {
                            Id = 4L,
                            Active = false,
                            CUIT = 135791113,
                            CompanyName = "Company4",
                            IdPerson = 4L
                        },
                        new
                        {
                            Id = 5L,
                            Active = true,
                            CUIT = 112233445,
                            CompanyName = "Company5",
                            IdPerson = 5L
                        },
                        new
                        {
                            Id = 6L,
                            Active = false,
                            CUIT = 998877665,
                            CompanyName = "Company6",
                            IdPerson = 6L
                        },
                        new
                        {
                            Id = 7L,
                            Active = true,
                            CUIT = 334455667,
                            CompanyName = "Company7",
                            IdPerson = 7L
                        },
                        new
                        {
                            Id = 8L,
                            Active = false,
                            CUIT = 556677889,
                            CompanyName = "Company8",
                            IdPerson = 8L
                        },
                        new
                        {
                            Id = 9L,
                            Active = true,
                            CUIT = 778899001,
                            CompanyName = "Company9",
                            IdPerson = 9L
                        },
                        new
                        {
                            Id = 10L,
                            Active = false,
                            CUIT = 102030405,
                            CompanyName = "Company10",
                            IdPerson = 10L
                        },
                        new
                        {
                            Id = 11L,
                            Active = true,
                            CUIT = 405060708,
                            CompanyName = "Company11",
                            IdPerson = 1L
                        },
                        new
                        {
                            Id = 12L,
                            Active = false,
                            CUIT = 203040506,
                            CompanyName = "Company12",
                            IdPerson = 2L
                        },
                        new
                        {
                            Id = 13L,
                            Active = true,
                            CUIT = 607080901,
                            CompanyName = "Company13",
                            IdPerson = 3L
                        },
                        new
                        {
                            Id = 14L,
                            Active = false,
                            CUIT = 102030405,
                            CompanyName = "Company14",
                            IdPerson = 4L
                        },
                        new
                        {
                            Id = 15L,
                            Active = true,
                            CUIT = 506070809,
                            CompanyName = "Company15",
                            IdPerson = 5L
                        },
                        new
                        {
                            Id = 16L,
                            Active = false,
                            CUIT = 102938475,
                            CompanyName = "Company16",
                            IdPerson = 6L
                        },
                        new
                        {
                            Id = 17L,
                            Active = true,
                            CUIT = 576869798,
                            CompanyName = "Company17",
                            IdPerson = 7L
                        },
                        new
                        {
                            Id = 18L,
                            Active = false,
                            CUIT = 384756392,
                            CompanyName = "Company18",
                            IdPerson = 8L
                        },
                        new
                        {
                            Id = 19L,
                            Active = true,
                            CUIT = 948573829,
                            CompanyName = "Company19",
                            IdPerson = 9L
                        },
                        new
                        {
                            Id = 20L,
                            Active = false,
                            CUIT = 201938475,
                            CompanyName = "Company20",
                            IdPerson = 10L
                        },
                        new
                        {
                            Id = 21L,
                            Active = true,
                            CUIT = 102938475,
                            CompanyName = "Company21",
                            IdPerson = 1L
                        },
                        new
                        {
                            Id = 22L,
                            Active = false,
                            CUIT = 938475920,
                            CompanyName = "Company22",
                            IdPerson = 2L
                        },
                        new
                        {
                            Id = 23L,
                            Active = true,
                            CUIT = 192837465,
                            CompanyName = "Company23",
                            IdPerson = 3L
                        },
                        new
                        {
                            Id = 24L,
                            Active = false,
                            CUIT = 920384756,
                            CompanyName = "Company24",
                            IdPerson = 4L
                        },
                        new
                        {
                            Id = 25L,
                            Active = true,
                            CUIT = 182736495,
                            CompanyName = "Company25",
                            IdPerson = 5L
                        },
                        new
                        {
                            Id = 26L,
                            Active = false,
                            CUIT = 204060708,
                            CompanyName = "Company26",
                            IdPerson = 6L
                        },
                        new
                        {
                            Id = 27L,
                            Active = true,
                            CUIT = 829384756,
                            CompanyName = "Company27",
                            IdPerson = 7L
                        },
                        new
                        {
                            Id = 28L,
                            Active = false,
                            CUIT = 102938475,
                            CompanyName = "Company28",
                            IdPerson = 8L
                        },
                        new
                        {
                            Id = 29L,
                            Active = true,
                            CUIT = 475829384,
                            CompanyName = "Company29",
                            IdPerson = 9L
                        },
                        new
                        {
                            Id = 30L,
                            Active = false,
                            CUIT = 394857294,
                            CompanyName = "Company30",
                            IdPerson = 10L
                        });
                });

            modelBuilder.Entity("ChallengeTecnico_Ears.Models.PersonModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeFile")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("T_Person");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Active = true,
                            Dni = 429052984,
                            EmployeeFile = 1001,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2L,
                            Active = true,
                            Dni = 973347851,
                            EmployeeFile = 1002,
                            Name = "Alice Smith"
                        },
                        new
                        {
                            Id = 3L,
                            Active = false,
                            Dni = 327813549,
                            EmployeeFile = 1003,
                            Name = "Bob Johnson"
                        },
                        new
                        {
                            Id = 4L,
                            Active = true,
                            Dni = 360802010,
                            EmployeeFile = 1004,
                            Name = "Emily Brown"
                        },
                        new
                        {
                            Id = 5L,
                            Active = false,
                            Dni = 157652163,
                            EmployeeFile = 1005,
                            Name = "Michael Wilson"
                        },
                        new
                        {
                            Id = 6L,
                            Active = true,
                            Dni = 990772592,
                            EmployeeFile = 1006,
                            Name = "Emma Davis"
                        },
                        new
                        {
                            Id = 7L,
                            Active = false,
                            Dni = 517109719,
                            EmployeeFile = 1007,
                            Name = "James Taylor"
                        },
                        new
                        {
                            Id = 8L,
                            Active = true,
                            Dni = 22460317,
                            EmployeeFile = 1008,
                            Name = "Olivia Martinez"
                        },
                        new
                        {
                            Id = 9L,
                            Active = false,
                            Dni = 453810075,
                            EmployeeFile = 1009,
                            Name = "William Jones"
                        },
                        new
                        {
                            Id = 10L,
                            Active = true,
                            Dni = 379323607,
                            EmployeeFile = 1010,
                            Name = "Sophia Anderson"
                        });
                });

            modelBuilder.Entity("ChallengeTecnico_Ears.Models.OfficeModel", b =>
                {
                    b.HasOne("ChallengeTecnico_Ears.Models.PersonModel", "Person")
                        .WithMany("Offices")
                        .HasForeignKey("IdPerson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ChallengeTecnico_Ears.Models.PersonModel", b =>
                {
                    b.Navigation("Offices");
                });
#pragma warning restore 612, 618
        }
    }
}
